AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  trip-restful-api

  Rest API to manage trips photos

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME: !Ref TripTable
        ENDPOINT_OVERRIDE: ""

Resources:

  CreateTripRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/trip-restful-api-1.0.0-SNAPSHOT-jar-with-dependencies.jar
      Handler: br.com.fiap.handler.CreateTripRecord::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TripTable
      Events:
        CreateTripRecord:
          Type: Api
          Properties:
            Path: /trips
            Method: post

  GetTripsRecordsByPeriodFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/trip-restful-api-1.0.0-SNAPSHOT-jar-with-dependencies.jar
      Handler: br.com.fiap.handler.GetTripRecordsByPeriod::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TripTable
      Events:
        GetTripRecordsByPeriod:
          Type: Api
          Properties:
            Path: /trips
            Method: get
            RequestParameters:
              - method.request.querystring.start
              - method.request.querystring.end

  GetTripRecordByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/trip-restful-api-1.0.0-SNAPSHOT-jar-with-dependencies.jar
      Handler: br.com.fiap.handler.GetTripRecordById::handleRequest
      Runtime: java8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TripTable
      Events:
        GetTripRecordById:
          Type: Api
          Properties:
            Path: /trips/{id}
            Method: get
            RequestParameters:
              - method.request.querystring.id

  TripTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trip
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: country
          AttributeType: S
        - AttributeName: city
          AttributeType: S
        - AttributeName: url
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:

  CreateTripRecordFunction:
    Description: "CreateTripRecord Lambda Function ARN"
    Value: !GetAtt CreateTripRecordFunction.Arn

  GetTripRecordsByPeriodFunction:
    Description: "GetTripRecordsByPeriod Lambda Function ARN"
    Value: !GetAtt GetTripRecordsByPeriodFunction.Arn

  GetTripRecordByIdFunction:
    Description: "GetTripRecordById Lambda Function ARN"
    Value: !GetAtt GetTripRecordByIdFunction.Arn