package br.com.fiap.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;


@DynamoDBTable(tableName = "trip")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
/** Trip : id, date (YYYY/MM/DD),
country, city, URL repository for photos **/
public class Trip {

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;

	@DynamoDBRangeKey(attributeName = "date")
	private String date;

	@DynamoDBAttribute(attributeName = "country")
	private String country;

	@DynamoDBAttribute(attributeName = "city")
	private String city;

	@DynamoDBAttribute(attributeName = "url")
	private String url;
}
